replicaCount: 1
image:
  apiGateway:
    repository: anwirisme/spring-petclinic-api-gateway
    tag: v1.0.0
  discoveryServer:
    repository: anwirisme/spring-petclinic-discovery-server
    tag: v1.0.0
  customersService:
    repository: anwirisme/spring-petclinic-customers-service
    tag: v1.0.0
  vetsService:
    repository: anwirisme/spring-petclinic-vets-service
    tag: v1.0.0
  visitsService:
    repository: anwirisme/spring-petclinic-visits-service
    tag: v1.0.0
  genaiService:
    repository: anwirisme/spring-petclinic-genai-service
    tag: v1.0.0
  adminServer:
    repository: anwirisme/spring-petclinic-admin-server
    tag: v1.0.0
  configServer:
    repository: anwirisme/spring-petclinic-config-server
    tag: v1.0.0
service:
  discoveryServer:
    port: 8761
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 31091
  configServer:
    port: 8888
    nodePort: 31089
  apiGateway:
    port: 8080
    nodePort: 30081
  zipkin:
    port: 9411
    nodePort: 30083
  prometheus:
    port: 9090
    nodePort: 30094
  grafana:
    port: 3000
    nodePort: 30100
loki:
  namespace: loki-staging
promtail:
  config:
    scrape_configs:
      job_name: kubernetes-pods-staging
      relabel_configs:
          regex: staging
namespace: staging
promtail:
  config:
    scrape_configs:
      job_name: "kubernetes-pods"
      relabel_configs:
        regex: "staging"
