apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server {{ .Values.service.discoveryServer.port }}; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: admin-server
          image: "{{ .Values.image.adminServer.repository }}:{{ .Values.image.adminServer.tag }}"
          ports:
            - containerPort: {{ .Values.service.adminServer.port }}
          env:

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_APPLICATION_NAME
              value: admin-server
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: admin-server:${HOSTNAME}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: admin-server
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - port: {{ .Values.service.adminServer.port }}
      targetPort: {{ .Values.service.adminServer.port }}
      nodePort: {{ .Values.service.adminServer.nodePort }}
  type: NodePort

