apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server {{ .Values.service.discoveryServer.port }}; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: api-gateway
          image: "{{ .Values.image.apiGateway.repository }}:{{ .Values.image.apiGateway.tag }}"
          ports:
            - containerPort: {{ .Values.service.apiGateway.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_APPLICATION_NAME
              value: api-gateway
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: api-gateway:${HOSTNAME}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: ZIPKIN_URL
              value: {{ .Values.zipkin.url }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.service.apiGateway.port }}
      targetPort: {{ .Values.service.apiGateway.port }}
      nodePort: {{ .Values.service.apiGateway.nodePort }}
  type: NodePort
