apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server {{ .Values.service.discoveryServer.port }}; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: visits-service
          image: "{{ .Values.image.visitsService.repository }}:{{ .Values.image.visitsService.tag }}"
          ports:
            - containerPort: {{ .Values.service.visitsService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: visits-service
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: ${spring.application.name}:${random.uuid}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
            - name: ZIPKIN_URL
              value: {{ .Values.zipkin.url }}
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - port: {{ .Values.service.visitsService.port }}
      targetPort: {{ .Values.service.visitsService.port }}
